default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beer_thirty_development
test:
  <<: *default
  database: beer_thirty_test
production:
  <<: *default
  database: beer_thirty_production
  username: beer_thirty
  password: <%= ENV['BEER_THIRTY_DATABASE_PASSWORD'] %>
