default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beer_thirty_development
test:
  <<: *default
  database: beer_thirty_test
production:
  url: <%= ENV['DATABASE_URL'] %>
